spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.h2.Driver
